import { Santri, SuratIzin, AbsensiRecord, HafalanRecord, PelanggaranRecord, KeuanganRecord, PesantrenConfig } from './types';

export const INITIAL_PESANTREN_CONFIG: PesantrenConfig = {
  namaPondok: "Pondok Pesantren Al-Azhar",
  subJudul: "Lembaga Pendidikan Al-Qur'an & Kitab Kuning",
  pengasuh: "KH. Ahmad Dahlan, M.Ag",
  alamat: "Jl. Pesantren No. 45, Kabupaten Sleman, D.I. Yogyakarta",
  telepon: "0812-3456-7890",
  email: "info@alazhar.ponpes.id",
};

export const INITIAL_SANTRI: Santri[] = [
  {
    id: "S-001",
    nis: "2024.01.001",
    noKK: "3312011204060001",
    nik: "3312011204060002",
    nama: "Muhammad Rayhan Al-Fatih",
    gender: "L",
    tempatLahir: "Yogyakarta",
    tanggalLahir: "2006-04-12",
    alamat: "Jl. Kaliurang Km 10, Candi Karang",
    rtRw: "RT 03 / RW 12",
    desaKelurahan: "Sardonoharjo",
    kecamatan: "Ngaglik",
    kabupatenKota: "Sleman",
    provinsi: "D.I. Yogyakarta",
    kodePos: "55581",
    kamar: "Al-Farabi 01",
    kelas: "3 Aliyah (Tahfizh)",
    namaWali: "H. Abdullah Syafi'i",
    hpWali: "081298765432",
    namaAyah: "H. Abdullah Syafi'i",
    pekerjaanAyah: "PNS / Guru",
    namaIbu: "Hj. Nur Hidayah",
    pekerjaanIbu: "Ibu Rumah Tangga",
    anakKe: 1,
    jumlahBersaudara: 3,
    status: "Aktif",
    tahunMasuk: 2021,
    catatan: "Ketua Pengurus Santri Putra"
  },
  {
    id: "S-002",
    nis: "2024.01.002",
    noKK: "3372011508070005",
    nik: "3372012008070003",
    nama: "Ahmad Zaki Mubarak",
    gender: "L",
    tempatLahir: "Solo",
    tanggalLahir: "2007-08-20",
    alamat: "Jl. Ahmad Yani No. 88, Banjarsari",
    rtRw: "RT 02 / RW 05",
    desaKelurahan: "Kadipiro",
    kecamatan: "Banjarsari",
    kabupatenKota: "Surakarta",
    provinsi: "Jawa Tengah",
    kodePos: "57136",
    kamar: "Al-Farabi 02",
    kelas: "2 Aliyah",
    namaWali: "Suryanto",
    hpWali: "081345678901",
    namaAyah: "Suryanto",
    pekerjaanAyah: "Wiraswasta",
    namaIbu: "Siti Rahmawati",
    pekerjaanIbu: "Pedagang",
    anakKe: 2,
    jumlahBersaudara: 4,
    status: "Aktif",
    tahunMasuk: 2022
  },
  {
    id: "S-003",
    nis: "2024.01.003",
    noKK: "3308051111060009",
    nik: "3308054511060004",
    nama: "Aisyah Nur Syafiqah",
    gender: "P",
    tempatLahir: "Magelang",
    tanggalLahir: "2006-11-05",
    alamat: "Jl. Pemuda No. 12, Muntilan",
    rtRw: "RT 01 / RW 03",
    desaKelurahan: "Sedayu",
    kecamatan: "Muntilan",
    kabupatenKota: "Magelang",
    provinsi: "Jawa Tengah",
    kodePos: "56412",
    kamar: "Khadijah 01",
    kelas: "3 Aliyah (Diniyah)",
    namaWali: "Hj. Mariam",
    hpWali: "085678901234",
    namaAyah: "Alm. Drs. H. Mustofa",
    pekerjaanAyah: "Almarhum",
    namaIbu: "Hj. Mariam",
    pekerjaanIbu: "Guru Madin",
    anakKe: 1,
    jumlahBersaudara: 2,
    status: "Aktif",
    tahunMasuk: 2021
  },
  {
    id: "S-004",
    nis: "2023.01.045",
    noKK: "3374021502040012",
    nik: "3374021502040008",
    nama: "Faris Ridho Rahman",
    gender: "L",
    tempatLahir: "Semarang",
    tanggalLahir: "2004-02-15",
    alamat: "Jl. Majapahit No. 204, Pedurungan",
    rtRw: "RT 04 / RW 08",
    desaKelurahan: "Gemah",
    kecamatan: "Pedurungan",
    kabupatenKota: "Semarang",
    provinsi: "Jawa Tengah",
    kodePos: "50191",
    kamar: "Ibnu Sina 03",
    kelas: "Lulus / Pasca Santri",
    namaWali: "Bambang K",
    hpWali: "081233445566",
    namaAyah: "Bambang Kuncoro",
    pekerjaanAyah: "Karyawan Swasta",
    namaIbu: "Sri Wahyuni",
    pekerjaanIbu: "PNS",
    anakKe: 3,
    jumlahBersaudara: 3,
    status: "Alumni",
    tahunMasuk: 2019,
    tahunAlumni: 2024,
    catatan: "Kuliah di UIN Sunan Kalijaga - Jurusan Ilmu Hadis"
  },
  {
    id: "S-005",
    nis: "2023.01.088",
    noKK: "3310043006050003",
    nik: "3310047006050001",
    nama: "Siti Fatimah Az-Zahra",
    gender: "P",
    tempatLahir: "Klaten",
    tanggalLahir: "2005-06-30",
    alamat: "Jl. Raya Jogja-Solo, Delanggu",
    rtRw: "RT 05 / RW 02",
    desaKelurahan: "Gatak",
    kecamatan: "Delanggu",
    kabupatenKota: "Klaten",
    provinsi: "Jawa Tengah",
    kodePos: "57471",
    kamar: "Aisyah 02",
    kelas: "Lulus / Pasca Santri",
    namaWali: "Subhan",
    hpWali: "087788990011",
    namaAyah: "Subhan",
    pekerjaanAyah: "Petani / Peternak",
    namaIbu: "Aminah",
    pekerjaanIbu: "Ibu Rumah Tangga",
    anakKe: 2,
    jumlahBersaudara: 3,
    status: "Alumni",
    tahunMasuk: 2020,
    tahunAlumni: 2024,
    catatan: "Pengajar TPQ & Pengusaha Herbal"
  },
  {
    id: "S-006",
    nis: "2024.01.004",
    noKK: "3302061001080007",
    nik: "3302061001080002",
    nama: "Bilal Nur Hidayat",
    gender: "L",
    tempatLahir: "Bantul",
    tanggalLahir: "2008-01-10",
    alamat: "Makam Imogiri, Girirejo",
    rtRw: "RT 02 / RW 01",
    desaKelurahan: "Girirejo",
    kecamatan: "Imogiri",
    kabupatenKota: "Bantul",
    provinsi: "D.I. Yogyakarta",
    kodePos: "55782",
    kamar: "Al-Ghazali 01",
    kelas: "1 Aliyah",
    namaWali: "Suparno",
    hpWali: "089900112233",
    namaAyah: "Suparno",
    pekerjaanAyah: "Perajin Batik",
    namaIbu: "Warsi",
    pekerjaanIbu: "Ibu Rumah Tangga",
    anakKe: 1,
    jumlahBersaudara: 2,
    status: "Aktif",
    tahunMasuk: 2023
  }
];

export const INITIAL_IZIN: SuratIzin[] = [
  {
    id: "IZN-2026-001",
    santriId: "S-002",
    nis: "2024.01.002",
    namaSantri: "Ahmad Zaki Mubarak",
    kamar: "Al-Farabi 02",
    kelas: "2 Aliyah",
    kategori: "Pulang",
    alasan: "Acara Pernikahan Kakak Kandung di Solo",
    tanggalKeluar: "2026-09-05",
    tanggalKembali: "2026-09-09",
    status: "Sedang Izin",
    penanggungJawab: "Ust. M. Ridwan",
    noHpPenanggungJawab: "08123456789",
    createdAt: "2026-09-04T10:00:00.000Z"
  },
  {
    id: "IZN-2026-002",
    santriId: "S-001",
    nis: "2024.01.001",
    namaSantri: "Muhammad Rayhan Al-Fatih",
    kamar: "Al-Farabi 01",
    kelas: "3 Aliyah (Tahfizh)",
    kategori: "Berobat",
    alasan: "Pemeriksaan Gigi ke RSUD",
    tanggalKeluar: "2026-09-01",
    tanggalKembali: "2026-09-01",
    status: "Sudah Kembali",
    penanggungJawab: "Ust. Agus Setiawan",
    createdAt: "2026-09-01T08:00:00.000Z"
  }
];

export const INITIAL_ABSENSI: AbsensiRecord[] = [
  {
    id: "ABS-001",
    tanggal: "2026-09-08",
    jenisKegiatan: "Shalat Subuh Berjamaah & Sorogan",
    santriId: "S-001",
    namaSantri: "Muhammad Rayhan Al-Fatih",
    kamar: "Al-Farabi 01",
    status: "Hadir"
  },
  {
    id: "ABS-002",
    tanggal: "2026-09-08",
    jenisKegiatan: "Shalat Subuh Berjamaah & Sorogan",
    santriId: "S-002",
    namaSantri: "Ahmad Zaki Mubarak",
    kamar: "Al-Farabi 02",
    status: "Izin",
    keterangan: "Pulang Izin Keluarga"
  },
  {
    id: "ABS-003",
    tanggal: "2026-09-08",
    jenisKegiatan: "Shalat Subuh Berjamaah & Sorogan",
    santriId: "S-003",
    namaSantri: "Aisyah Nur Syafiqah",
    kamar: "Khadijah 01",
    status: "Hadir"
  }
];

export const INITIAL_HAFALAN: HafalanRecord[] = [
  {
    id: "HAF-001",
    santriId: "S-001",
    namaSantri: "Muhammad Rayhan Al-Fatih",
    tanggal: "2026-09-07",
    juz: 15,
    surah: "Al-Kahfi",
    ayatAwal: 1,
    ayatAkhir: 30,
    predikat: "Mumtaz (Sangat Baik)",
    ustadz: "Ust. M. Ridwan"
  },
  {
    id: "HAF-002",
    santriId: "S-003",
    namaSantri: "Aisyah Nur Syafiqah",
    tanggal: "2026-09-06",
    juz: 29,
    surah: "Al-Mulk",
    ayatAwal: 1,
    ayatAkhir: 30,
    predikat: "Mumtaz (Sangat Baik)",
    ustadz: "Ustadzah Fatimah"
  }
];

export const INITIAL_PELANGGARAN: PelanggaranRecord[] = [
  {
    id: "PLG-001",
    santriId: "S-006",
    namaSantri: "Bilal Nur Hidayat",
    tanggal: "2026-09-02",
    jenisPelanggaran: "Terlambat Shalat Berjamaah Subuh",
    tingkat: "Ringan",
    poin: 5,
    hukuman: "Membaca Al-Qur'an 1 Juz di Serambi Masjid",
    statusTazcir: "Sudah Selesai"
  }
];

export const INITIAL_KEUANGAN: KeuanganRecord[] = [
  {
    id: "KEU-001",
    santriId: "S-001",
    namaSantri: "Muhammad Rayhan Al-Fatih",
    bulan: "September 2026",
    jumlah: 350000,
    status: "Lunas",
    tanggalBayar: "2026-09-02"
  },
  {
    id: "KEU-002",
    santriId: "S-002",
    namaSantri: "Ahmad Zaki Mubarak",
    bulan: "September 2026",
    jumlah: 350000,
    status: "Belum Lunas"
  },
  {
    id: "KEU-003",
    santriId: "S-003",
    namaSantri: "Aisyah Nur Syafiqah",
    bulan: "September 2026",
    jumlah: 350000,
    status: "Lunas",
    tanggalBayar: "2026-09-03"
  }
];
